### ISSUE TITLE
TCX from Garmin is missing trackpoints

### ISSUE THREAD

**Issue by elskewe** [Antash/exercisync#40]
I connected Garmin Connect and Dropbox. The tcx files that are synced to the Dropbox are a lot smaller than they should be (less than 1/5 of the expected size) and the trackpoints are only about every 5 or more seconds.

**Comment by Antash** [comment]
@elskewe can you please provide some example source activity and tcx file links?

**Comment by elskewe** [comment]
For privacy reasons I send the file via email

**Comment by Antash** [comment]
For the first look it is an garmin optimization. Evercisync use same web API GarminConnect portal use to display activily track and it is fair enough they decided to compress data because nobody cares how many track points displayed on a map byt everyone want map to be fast and responsive.

I will replace existing approach with the direct export to tcx.

Thank you for reporting!

**Comment by Antash** [comment]
@elskewe sorry for such a late fix. Resolved.
